vich_uploader:
  db_driver: orm
  mappings:
    product_images:
      uri_prefix: /uploads/products
      upload_destination: "%kernel.project_dir%/public/uploads/products"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      delete_on_remove: true
      delete_on_update: true
      inject_on_load: false

    professor:
      uri_prefix: /uploads/professors
      upload_destination: "%kernel.project_dir%/public/uploads/professors"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    outfit:
      uri_prefix: /uploads/outfits
      upload_destination: "%kernel.project_dir%/public/uploads/outfits"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    event:
      uri_prefix: /uploads/events
      upload_destination: "%kernel.project_dir%/public/uploads/events"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    sponsor:
      uri_prefix: /uploads/sponsors
      upload_destination: "%kernel.project_dir%/public/uploads/sponsors"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
