# Import des contrôleurs avec attributs
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# Route vers un template sans contrôleur
bureau:
    path: /membresBureau
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
       template: 'home/administration.html.twig'

mention:
    path: /mentionslegales
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
       template: 'home/mentionslegales.html.twig'

gala:
    path: /gala
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
       template: 'event/gala.html.twig'